# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 20765
    url: 20765/
    weight: 20
  - name: Research
    url: research/
    weight: 30
  - name: Birds
    url: birds/
    weight: 40
  - name: CV
    url: uploads/Rezume.pdf
    weight: 50
